version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app  # Sincronizar arquivos locais com o contêiner para hot-reload
      - /app/node_modules  # Evitar conflito de dependências
      - ./static/build:/app/static/build  # Volume compartilhado para os arquivos estáticos gerados pelo Webpack
      - ./migrations:/app/migrations  # Persistir migrações no host
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0 --port=8000"

  webpack:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - ./static/build:/app/static/build  # Volume compartilhado para os arquivos gerados pelo Webpack
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: bash -c "npm run watch"