"""Configuração inicial

Revision ID: ec419bd9bcb7
Revises: 
Create Date: 2024-12-06 00:30:09.180718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec419bd9bcb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_resposta', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK_Respostas_NumeroResposta', type_='foreignkey')
        batch_op.create_foreign_key(None, 'NumeroResposta', ['numero_resposta'], ['IdNumeroResposta'], ondelete='CASCADE')
        batch_op.drop_column('NumeroResposta')

    with op.batch_alter_table('respostas_perguntas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Respostas', ['id_resposta'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_perguntas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NumeroResposta', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_Respostas_NumeroResposta', 'NumeroResposta', ['NumeroResposta'], ['IdNumeroResposta'], ondelete='CASCADE')
        batch_op.drop_column('numero_resposta')

    # ### end Alembic commands ###
